# Generated by Django 5.2 on 2025-05-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerinsight",
            options={
                "ordering": ["-total_spend"],
                "permissions": [
                    ("view_analytics_dashboard", "Может просматривать аналитическую панель")
                ],
                "verbose_name": "Аналитика по клиенту",
                "verbose_name_plural": "Аналитика по клиентам",
            },
        ),
        migrations.AlterModelOptions(
            name="customersegment",
            options={
                "ordering": ["-loyalty_index", "name"],
                "permissions": [
                    ("view_customer_segmentation", "Может просматривать сегментацию клиентов")
                ],
                "verbose_name": "Сегмент клиентов",
                "verbose_name_plural": "Сегменты клиентов",
            },
        ),
        migrations.AlterModelOptions(
            name="dailysales",
            options={
                "ordering": ["-date", "restaurant"],
                "permissions": [("view_sales_report", "Может просматривать отчет о продажах")],
                "verbose_name": "Ежедневные продажи",
                "verbose_name_plural": "Ежедневные продажи",
            },
        ),
        migrations.AlterModelOptions(
            name="nutritionalanalytics",
            options={
                "ordering": ["-date_period", "restaurant"],
                "permissions": [
                    ("view_nutritional_analytics", "Может просматривать анализ пищевой ценности")
                ],
                "verbose_name": "Анализ пищевой ценности",
                "verbose_name_plural": "Анализ пищевой ценности",
            },
        ),
        migrations.AlterModelOptions(
            name="popularitem",
            options={
                "ordering": ["-total_orders", "menu_item__name"],
                "permissions": [("view_menu_analysis", "Может просматривать анализ меню")],
                "verbose_name": "Популярное блюдо",
                "verbose_name_plural": "Популярные блюда",
            },
        ),
        migrations.AlterModelOptions(
            name="staffperformance",
            options={
                "ordering": ["-date_period", "restaurant", "staff__last_name"],
                "permissions": [
                    ("view_staff_performance", "Может просматривать эффективность персонала")
                ],
                "verbose_name": "Эффективность сотрудника",
                "verbose_name_plural": "Эффективность сотрудников",
            },
        ),
        migrations.AlterModelOptions(
            name="tableoccupancy",
            options={
                "ordering": ["-date", "restaurant", "table__number"],
                "permissions": [("view_table_occupancy", "Может просматривать занятость столиков")],
                "verbose_name": "Занятость столика",
                "verbose_name_plural": "Занятость столиков",
            },
        ),
    ]
