# Generated by Django 5.2 on 2025-05-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cookingstation",
            options={
                "ordering": ["restaurant", "name"],
                "permissions": [("manage_cooking_stations", "Может управлять кухонными станциями")],
                "verbose_name": "Кухонная станция",
                "verbose_name_plural": "Кухонные станции",
            },
        ),
        migrations.AlterModelOptions(
            name="kitchenevent",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_kitchen_log", "Может просматривать журнал кухни"),
                    ("view_kitchen_dashboard", "Может просматривать панель кухни"),
                ],
                "verbose_name": "Событие на кухне",
                "verbose_name_plural": "События на кухне",
            },
        ),
        migrations.AlterModelOptions(
            name="kitchenorder",
            options={
                "ordering": ["-created_at"],
                "permissions": [("view_kitchen_order", "Может просматривать заказы на кухне")],
                "verbose_name": "Заказ на кухне",
                "verbose_name_plural": "Заказы на кухне",
            },
        ),
        migrations.AlterModelOptions(
            name="kitchenqueue",
            options={
                "ordering": ["restaurant", "order", "name"],
                "permissions": [("view_kitchen_queue", "Может просматривать очередь на кухне")],
                "verbose_name": "Очередь кухни",
                "verbose_name_plural": "Очереди кухни",
            },
        ),
    ]
