# Generated by Django 5.2 on 2025-05-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["category", "order_in_category", "name"],
                "permissions": [
                    ("view_menu_item", "Может просматривать позиции меню"),
                    ("manage_menu", "Может управлять меню"),
                    ("view_menu", "Может просматривать меню"),
                ],
                "verbose_name": "Позиция меню",
                "verbose_name_plural": "Позиции меню",
            },
        ),
    ]
