# Generated by Django 5.2 on 2025-05-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={
                "ordering": ["-created_at"],
                "permissions": [("manage_discounts", "Может управлять скидками")],
                "verbose_name": "Скидка/Промокод",
                "verbose_name_plural": "Скидки/Промокоды",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "permissions": [("view_order_history", "Может просматривать историю заказов")],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
